theme: jekyll-theme-minimal
logo: Images/JarvisLogo.png
object: '<iframe data-blogger-escaped-allowfullscreen="" src="https://www.youtube.com/embed/zV5GBg2qbNE" width="480" height="270" frameborder="0"></iframe>'
