
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTION ADD AND COLON COMMA CREATE DELETE DIVIDE FORGET ID JOKE LC LEARN LP MOVE MULTIPLY Modulo NOT NUMBER OR PERIOD PLUS POWER RANDOM RC RESPONSE ROLLDICE ROOT RP RULES SAVE SEARCHIMAGE SEMICOLON STRING SUBTRACT SUM UNKNOWN UPDATEresponse_rule : STRING COLON RESPONSE LP STRING RP SEMICOLON'
    
_lr_action_items = {'STRING':([0,5,],[2,6,]),'$end':([1,8,],[0,-1,]),'COLON':([2,],[3,]),'RESPONSE':([3,],[4,]),'LP':([4,],[5,]),'RP':([6,],[7,]),'SEMICOLON':([7,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'response_rule':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> response_rule","S'",1,None,None,None),
  ('response_rule -> STRING COLON RESPONSE LP STRING RP SEMICOLON','response_rule',7,'p_response_rule','JarvisYacc.py',52),
]
